version: "3"

services:
  darpan-nginx:
    image: darpan/nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - "/mnt/crucial-500/Darpan-Pictures:/Pictures"

  darpan-backend:
    image: darpan/backend
    build: ./darpan-backend
    volumes:
      - "/mnt/crucial-500/Darpan-Pictures:/Pictures"

  darpan-authentication-server:
    image: darpan/authentication-server
    build: ./darpan-authentication-server
