version: "3"

services:
  darpan:
    image: darpan
    build: .
    ports:
      - "80:80"
    volumes:
      - "/ext/Pictures:/Pictures"
      - "darpanDB:/darpan-backend/db/sqlite"
    environment:
      - SECRET=$C&F)J@NcRfUjXn2r5u8x!A%D*G-KaPd
      - MAPAPIKEY=MOI3HYNBtHgay8O6XUEnFT24lL8KMt1jWq8Zo4mHEm4

volumes:
  darpanDB:
